name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chat:
    name: Checks
    timeout-minutes: 15
    runs-on: [macos-latest]
    if: (!contains(github.event.pull_request.title, '[skip ci]'))
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/cache@v3.0.11
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle check || bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Fasterer
        run: bundle exec fasterer
      - name: Snyk
        run: |
          npm install -g snyk
          snyk test --policy-path=.snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
